### ISSUE TITLE
elastalert-server error with praeco helm chart install

### ISSUE THREAD

**Issue by redaER7** [daichi703n/praeco-helm#13]
Hello,
Here, I am trying to set up Praeco using helm with an ES server version 8, I installed `elastalert2` from https://github.com/jertel/elastalert2/tree/master/chart/elastalert2 with:
```bash
helm upgrade -i elastalert2 elastalert2/elastalert2 \
  --namespace $NAMESPACE \
  --version 2.15.0 \
  -f values.yaml
```
with 
```values.yaml
writebackIndex: elastalert_status
image:
  repository: jertel/elastalert2
  tag: 2.15.0
elasticsearch:
  host: $ES_HOST
  # elasticsearch port
  port: 9200
  useSsl: "False" 
  ```
 Logs are healthy
```bash
 Reading Elastic 8 index mappings:
Reading index mapping 'es_mappings/8/silence.json'
Reading index mapping 'es_mappings/8/elastalert_status.json'
Reading index mapping 'es_mappings/8/elastalert.json'
Reading index mapping 'es_mappings/8/past_elastalert.json'
Reading index mapping 'es_mappings/8/elastalert_error.json'
New index elastalert_status created
Done
```
Now when installing praeco chart:
```bash
helm upgrade -i praeco daichi703n/praeco \
  --namespace $NAMESPACE \
  -f values.yaml
```
chart is deployed
```bash
praeco       	tp-demo-2	1       	2024-05-28 15:19:40.227077 +0200 CEST	deployed	praeco-0.1.7         	1.8.13
```
but, I have the following issue on `elastalert-server` container
```bash
...
15:04:26.229Z  INFO elastalert-server: ProcessController:  Creating index
15:04:26.470Z  INFO elastalert-server:
    ProcessController:  Reading Elastic 8 index mappings:
    Reading index mapping 'es_mappings/8/silence.json'
    Reading index mapping 'es_mappings/8/elastalert_status.json'
    Reading index mapping 'es_mappings/8/elastalert.json'
    Reading index mapping 'es_mappings/8/past_elastalert.json'
    Reading index mapping 'es_mappings/8/elastalert_error.json'
    Index elastalert_status already exists. Skipping index creation.

15:04:26.470Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
15:04:26.471Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
15:04:26.479Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 37)
15:04:26.482Z ERROR elastalert-server:
    Server:  Starting server failed with error: TypeError: Cannot read properties of undefined (reading 'relative')
        at ElastalertServer.getDataFolder (/opt/elastalert-server/src/elastalert_server.js:141:28)
        at TestController._getTestFolder (/opt/elastalert-server/src/controllers/test/index.js:169:35)
        at new TestController (/opt/elastalert-server/src/controllers/test/index.js:18:28)
        at callback (/opt/elastalert-server/src/elastalert_server.js:97:32)
        at forEach (/opt/elastalert-server/src/common/config/server_config.js:59:9)
        at Array.forEach (<anonymous>)
        at /opt/elastalert-server/src/common/config/server_config.js:58:22
15:04:26.482Z  INFO elastalert-server: Server:  Stopping server
```
Any ideas above above issue?
Thanks,

**Comment by daichi703n** [comment]
@redaER7 maybe same as: https://github.com/daichi703n/praeco-helm/issues/8

You have to set vars for connecting to your ES.
https://github.com/daichi703n/praeco-helm/blob/master/vars.yml.example#L1-L7

You don't need to deploy elastalert2 chart, because of elastalert-server that is deployed with praeco-helm dependency contains elastalert2.

**Comment by redaER7** [comment]
@daichi703n 
I didn't add username nor passowird, since the ES host is freely accessible, no users credentials are needed,
as in the logs, I see `...Reading Elastic 8 index mappings:..`, I suppose it already established connection with ES host

**Comment by daichi703n** [comment]
@redaER7 You are correct. ElastAlert can be connected to ES. But, please set these params for templating even though no credential needed. like: `dummy` / `dummy`
