### ISSUE TITLE
Elastalert server is restarting again and again

### ISSUE THREAD

**Issue by Arun-Ghosh** [daichi703n/praeco-helm#8]
Hi @daichi703n - san,

I am trying to use this helm. I have updated values in vars.yml. And using below command to install

`helm install praeco --namespace default daichi703n/praeco -f vars.yml`

Result of which is :

NAME: praeco
LAST DEPLOYED: Fri May 19 12:47:41 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=praeco,app.kubernetes.io/instance=praeco" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:8080

praeco is running fine, but praeco-elastalert is restarting again and again. with below error.

`10:56:40.655Z  INFO elastalert-server: Router:  Listening for GET request on /mapping/:index.
10:56:40.656Z  INFO elastalert-server: Router:  Listening for POST request on /search/:index.
10:56:40.656Z  INFO elastalert-server: Router:  Listening for GET request on /config.
10:56:40.675Z  INFO elastalert-server: ProcessController:  Starting ElastAlert
10:56:40.675Z  INFO elastalert-server: ProcessController:  Creating index
10:56:41.022Z  INFO elastalert-server:
    ProcessController:  Reading Elastic 7 index mappings:
    Reading index mapping 'es_mappings/7/silence.json'
    Reading index mapping 'es_mappings/7/elastalert_status.json'
    Reading index mapping 'es_mappings/7/elastalert.json'
    Reading index mapping 'es_mappings/7/past_elastalert.json'
    Reading index mapping 'es_mappings/7/elastalert_error.json'
    Index elastalert_status already exists. Skipping index creation.
    
10:56:41.022Z  INFO elastalert-server: ProcessController:  Index create exited with code 0
10:56:41.022Z  INFO elastalert-server: ProcessController:  Starting elastalert with arguments [none]
10:56:41.039Z  INFO elastalert-server: ProcessController:  Started Elastalert (PID: 36)
10:56:41.044Z ERROR elastalert-server:
    Server:  Starting server failed with error: TypeError: Cannot read properties of undefined (reading 'relative')
        at ElastalertServer.getDataFolder (/opt/elastalert-server/src/elastalert_server.js:141:28)
        at TestController._getTestFolder (/opt/elastalert-server/src/controllers/test/index.js:169:35)
        at new TestController (/opt/elastalert-server/src/controllers/test/index.js:18:28)
        at callback (/opt/elastalert-server/src/elastalert_server.js:97:32)
        at forEach (/opt/elastalert-server/src/common/config/server_config.js:59:9)
        at Array.forEach (<anonymous>)
        at /opt/elastalert-server/src/common/config/server_config.js:58:22
10:56:41.045Z  INFO elastalert-server: Server:  Stopping server
10:56:41.045Z  INFO elastalert-server: ProcessController:  Stopping ElastAlert (PID: 36)
10:56:41.048Z  INFO elastalert-server: Server:  Server stopped. Bye!
npm notice 
npm notice New major version of npm available! 8.19.3 -> 9.6.7
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.7>
npm notice Run `npm install -g npm@9.6.7` to update!
npm notice`

Could you please help me to debug it.

**Comment by Arun-Ghosh** [comment]
Sorry my bad. Fix the issue. I missed to give the Username and password.
